	call git rm      admin/class-import-aioseo.php
	call git rm      admin/class-import-external.php
	call git rm      admin/class-import-jetpack.php
	call git rm      admin/class-import-woothemes-seo.php
	call git rm      admin/class-import-wpseo.php
	call git rm      admin/class-import.php
	call git rm      admin/class-social acebook orm.php
	call git rm      admin/class-social acebook.php
	call git rm      admin/class-stop-words.php
	call git rm      admin/import/class-import-aioseo-hooks.php
	call git rm      admin/import/class-import-hooks.php
	call git rm      admin/import/class-import-wpseo-hooks.php
	call git rm      admin/menu/class-submenu-hider.php
	call git rm      admin/pages/advanced.php
	call git rm      admin/pages/xml-sitemaps.php
	call git rm      admin/views/about.php
	call git rm      admin/views/tabs/advanced/breadcrumbs.php
	call git rm      admin/views/tabs/advanced/permalinks.php
	call git rm      admin/views/tabs/advanced/rss.php
	call git rm      admin/views/tabs/dashboard/general.php
	call git rm      admin/views/tabs/dashboard/knowledge-graph.php
	call git rm      admin/views/tabs/dashboard/security.php
	call git rm      admin/views/tabs/metas/home.php
	call git rm      admin/views/tabs/metas/other.php
	call git rm      admin/views/tabs/sitemaps/exclude-post.php
	call git rm      admin/views/tabs/sitemaps/general.php
	call git rm      admin/views/tabs/sitemaps/post-types.php
	call git rm      admin/views/tabs/sitemaps/taxonomies.php
	call git rm      admin/views/tabs/sitemaps/user-sitemap.php
	call git rm      css/dist/admin-global-580-rtl.min.css
	call git rm      css/dist/admin-global-580.min.css
	call git rm      css/dist/alerts-580-rtl.min.css
	call git rm      css/dist/alerts-580.min.css
	call git rm      css/dist/filter-explanation-580-rtl.min.css
	call git rm      css/dist/filter-explanation-580.min.css
	call git rm      css/dist/metabox-580-rtl.min.css
	call git rm      css/dist/metabox-580.min.css
	call git rm      css/dist/toggle-switch-580-rtl.min.css
	call git rm      css/dist/toggle-switch-580.min.css
	call git rm      css/dist/yoast-components-580-rtl.min.css
	call git rm      css/dist/yoast-components-580.min.css
	call git rm      css/dist/yoast-extensions-580-rtl.min.css
	call git rm      css/dist/yoast-extensions-580.min.css
	call git rm      css/dist/yst_plugin_tools-580-rtl.min.css
	call git rm      css/dist/yst_plugin_tools-580.min.css
	call git rm      css/xml-sitemap-xsl.php
	call git rm      deprecated/class-googleplus.php
	call git rm      deprecated/class-onpage-email-presenter.php
	call git rm      deprecated/class-onpage-notifier.php
	call git rm      deprecated/class-snippet-preview.php
	call git rm      deprecated/class-yoast-textstatistics.php
	call git rm      inc/class-wpseo-advanced-settings.php
	call git rm      inc/options/class-wpseo-option-internallinks.php
	call git rm      inc/options/class-wpseo-option-permalinks.php
	call git rm      inc/options/class-wpseo-option-rss.php
	call git rm      inc/options/class-wpseo-option-xml.php
	call git rm      js/dist/configuration-wizard-580.min.js
	call git rm      js/dist/jquery.tablesorter.min.js
	call git rm      js/dist/wp-seo-admin-580.min.js
	call git rm      js/dist/wp-seo-admin-global-580.min.js
	call git rm      js/dist/wp-seo-admin-gsc-580.min.js
	call git rm      js/dist/wp-seo-babel-polyfill-580.min.js
	call git rm      js/dist/wp-seo-dashboard-widget-580.min.js
	call git rm      js/dist/wp-seo-help-center-580.min.js
	call git rm      js/dist/wp-seo-metabox-580.min.js
	call git rm      js/dist/wp-seo-post-scraper-580.min.js
	call git rm      js/dist/wp-seo-recalculate-580.min.js
	call git rm      js/dist/wp-seo-replacevar-plugin-580.min.js
	call git rm      js/dist/wp-seo-term-scraper-580.min.js
